
services:
  load_balancer:
    build:
      context: .
      dockerfile: Docker.loadbalancer
    image: myproject_load_balancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
    privileged: true

  server1:
    build:
      context: .
      dockerfile: Docker.server
      image: myproject_server
    container_name: server_1
    ports:
      - "5001:5000"
    networks:
      - app-network
    environment:
      - SERVER_NAME=server1

  server2:
    build:
      context: .
      dockerfile: Docker.server
      image: myproject_server
    container_name: server_2
    ports:
      - "5002:5000"
    networks:
      - app-network
    environment:
      - SERVER_NAME=server2

  server3:
    build:
      context: .
      dockerfile: Docker.server
      image: myproject_server
    container_name: server_3
    ports:
      - "5003:5000"
    networks:
      - app-network
    environment:
      - SERVER_NAME=server3

networks:
  app-network:
    driver: bridge

